### PR TITLE
Adding a few extra images

### PR DESCRIPTION
**Pull request by oparoz**
Trying to improve the sample

@jancborchardt

### CODE REVIEW

**Comment by jancborchardt** [comment]
Nice! Although logo-wide is not in use anymore and should be removed. :)

**Comment by oparoz** [comment]
Well, it's more about the content than it's use :P

**Comment by jancborchardt** [comment]
I know, but still that logo is wrong and should not be used anywhere anymore. :) If you remove that the other additions are fine I guess.

**Comment by PVince81** [comment]
closing due to lack of feedback / abandoned

**Pull request closed without merging**
